### PR TITLE
feat: truncate text overflow with ellipsis

### LINKED ISSUE #163: Handle long voter names overflow
Handle long voter names overflow using ellipsis

### PR DESCRIPTION
**Pull request by BreadGenie**
fix #163 

Truncated poll name, poll description and the voter's names 

## Before

Screenshot from 2022-11-28 15-51-36
Screenshot from 2022-11-28 16-00-40

## After
Screenshot from 2022-11-28 15-50-59
Screenshot from 2022-11-28 16-00-00

### CODE REVIEW

**Comment by BreadGenie** [comment]
Seems like I overdid it
Should I not deal with the overflow in poll name and poll description?

**Comment by AnandBaburajan** [comment]
Thanks @BreadGenie! : ) Can you also set a reasonable max character limit for those fields?

**Comment by BreadGenie** [comment]
I've set a max character limit. Feel free to recommend changes to those values.

**Comment by AnandBaburajan** [comment]
Thanks @BreadGenie!

**Pull request merged**
